List repos
GET https://api.github.com/user/repos?affiliation=owner
Accept: application/vnd.github+json"
X-GitHub-Api-Version: 2022-11-28
Authorization: Bearer ghu_UXQqDLA0f4wM3NwSgG1PDLahuB2usu2kgAeP

### 

GET https://api.github.com/user
Accept: application/vnd.github+json"
X-GitHub-Api-Version: 2022-11-28
Authorization: Bearer ghu_UXQqDLA0f4wM3NwSgG1PDLahuB2usu2kgAeP

###

GET https://api.github.com/user/installations
Accept: application/vnd.github+json"
Authorization: Bearer ghu_UXQqDLA0f4wM3NwSgG1PDLahuB2usu2kgAeP
X-GitHub-Api-Version: 2022-11-28

###
GET https://api.github.com/app
Accept: application/vnd.github+json"
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzQ1ODI4ODgsImV4cCI6MTY3NDU4MzU0OCwiaXNzIjoiMjgyNzIyIn0.LsIDeKLcp_fAPT2YP3TIPNh1DY63hkJE0d83kouR9J1uQvzdbplS-Qd9-6u5gFAbmhvyEqxY7PbYr_8NMEGMqyWYFmZmWJFCrpUdH7aDxijSouAZP81NBjuX2f9ZB4UqNjFbJAVzP3M0h88QyFP0vEYfoSj6ZWH8Sxkk0n2IpiyrpjydCNSZ2hYaXtwGG_tQcORFuO9BGu3RFwmoHXppS5GQ7e5jV_HKCKw6C5NgoeL4C2CV3XvoG4spQT_AzrM_7jQaSqSRBlPPOR1wx270-Sf-n1YCjxHYjB8Wi9UtGxiVEQb8DqxIslkhpVAmRP3A-1u4O2yvPOJ3WuDSJFZsjA
X-GitHub-Api-Version: 2022-11-28

###
POST https://api.github.com/app/installations/:installation_id/access_tokens
Accept: application/vnd.github+json"
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzQ1ODI4ODgsImV4cCI6MTY3NDU4MzU0OCwiaXNzIjoiMjgyNzIyIn0.LsIDeKLcp_fAPT2YP3TIPNh1DY63hkJE0d83kouR9J1uQvzdbplS-Qd9-6u5gFAbmhvyEqxY7PbYr_8NMEGMqyWYFmZmWJFCrpUdH7aDxijSouAZP81NBjuX2f9ZB4UqNjFbJAVzP3M0h88QyFP0vEYfoSj6ZWH8Sxkk0n2IpiyrpjydCNSZ2hYaXtwGG_tQcORFuO9BGu3RFwmoHXppS5GQ7e5jV_HKCKw6C5NgoeL4C2CV3XvoG4spQT_AzrM_7jQaSqSRBlPPOR1wx270-Sf-n1YCjxHYjB8Wi9UtGxiVEQb8DqxIslkhpVAmRP3A-1u4O2yvPOJ3WuDSJFZsjA
X-GitHub-Api-Version: 2022-11-28